### PR TITLE
Overhaul build system and add license

### PR DESCRIPTION
**Pull request by sharkwouter**
The `create-matrix.js` script comes from the vitasdk/packages repo, which has no license. Replacing it would allow us to add a license to this repo and to fix some issues we have. I wrote the replacement script from scratch using python only using the standard library.

The advantages of this change will be:

- All package builds in the pipeline will be started at the same time. No more waiting for the initial step for packages with dependencies.
- Packages will be build with only their dependencies available and no other packages. Making sure there are never dependencies missing for a package.
- `install.sh` will use the new script to resolve dependencies as well. Right now it has some issues with that. This part still needs to be done, which is why this is a draft.

Downsides:

- We need permission from all contributors to this repo for the license change. I think this should be doable. This is why I am creating this now, despite this PR not being fully done, since it might take some time.
- For each package the directory name and the package name have to be the same with this script. I could probably fix this, but I think this is fine.

So to the following contributors, would it be okay to put the unlicense on your work on this repo?

- [x] @sharkwouter
- [x] @fjtrujy 
- [x] @bucanero 
- [x] @tpimh 
- [x] @wally4000 
- [x] @diamant3 
- [x] @davidgfnet 
- [x] @IridescentRose 
- [x] @stdgregwar 
- [x] @KorigamiK 

Please comment your answer below, then I can mark you off on the list.

### CODE REVIEW

**Comment by tpimh** [comment]
I am totally fine with the license change.

Do we know the origin of SDL2 sample code? Who is the original author and where was it published initially? Perhaps @bucanero can tell more.

**Comment by wally4000** [comment]
No problems here

**Comment by stdgregwar** [comment]
I'm fine with the license change as well.

**Comment by sharkwouter** [comment]
> Do we know the origin of SDL2 sample code? Who is the original author and where was it published initially? Perhaps @bucanero can tell more.

No worries, @diamant3 and me wrote those.

**Comment by fjtrujy** [comment]
It is fine! Go ahead!

**Comment by diamant3** [comment]
Yes, it's fine to me too

**Comment by KorigamiK** [comment]
Fine with me! Go ahead :)

**Comment by bucanero** [comment]
All good, go ahead! 👍🏻

**Comment by IridescentRose** [comment]
Go ahead

**Comment by davidgfnet** [comment]
Go ahead!

**Pull request merged**
