### PR TITLE
fix pkgconfig sdl

### PR DESCRIPTION
**Pull request by diamant3**

### CODE REVIEW

**Review by sharkwouter — CHANGES_REQUESTED** [review]
This one still has `-L/usr/local/pspdev/psp/sdk/lib -L/usr/local/pspdev/psp` in both the pkgconfig file and the sdl-config binary.

**Comment by diamant3** [comment]
I will convert it to draft for now. I will fix it later, thanks!

**Comment by diamant3** [comment]
Please review it again, thank you!

**Comment by sharkwouter** [comment]
Looks good, well done!

**Pull request merged**
