### PR TITLE
fix pkgconfig-libpng

### PR DESCRIPTION
**Pull request by diamant3**

### CODE REVIEW

**Comment by diamant3** [comment]
is libpng and libpng16 are the same?, because they are in the same `pkg/psp/lib/pkgconfig/` directory

same as libjpeg and libturbojpeg in PR #65 that already merged, thanks!

**Review by sharkwouter — CHANGES_REQUESTED** [review]
Thanks for this PR. It seems the includedir is incorrect, though. It should be `includedir=${prefix}/include/libpng16`. The libpng16-config binary also requires the same treatment as the pc file.

Thanks for working on this, it's really appreciated.

**Comment by sharkwouter** [comment]
Yeah, libpng is a symlink to libpng16. You can ignore that one for now.

**Comment by diamant3** [comment]
Done. Please review it again, thanks!

**Comment by sharkwouter** [comment]
Thanks for the fix!

**Pull request merged**
